name: teststuff
on: 
  push
jobs:
  one:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v1
        with:
          node-version: '12'
      - name: Install
        run: |
          npm install 
      - name: TS Session
        uses: ./actions/run
        with:
          ts-org:      testorg1
          ts-username: testuser
          ts-password: ${{ secrets.TS_Password }}
          gh-repo:     testRepoTEMP
          ts-project:  munderseth:testRepoTEMP
      - name: Test TS Org Setup
        uses: ./actions/org/create
        with:
          ts-org:      testopen01
          ts-username: testuser
          ts-password: ${{ secrets.TS_Password }}
      - name: Test TS Org Teardown
        uses: ./actions/org/cancel
        with:
          ts-org:      testopen01
          ts-username: testuser
          ts-password: ${{ secrets.TS_Password }}
      - name: Test Repo Setup
        uses: ./actions/repo/setup
        with:
          temp-org-name:  munderseth
          temp-repo-name: testspace.test.manual
          org-name:       munderseth
          repo-name:      test01
          accesstoken:    ${{ secrets.GH_Admin }}
      - name: Test Repo Teardown
        uses: ./actions/repo/teardown
        with:
          org-name:    munderseth
          repo-name:   test01
          accesstoken: ${{ secrets.GH_Admin }}
