name: teststuff
on: 
  push
jobs:
  one:
    runs-on: ubuntu-latest
    steps:
      - name: Test TS Org Setup
        uses: ./actions/org/create
        with:
          ts-org:      testopen01
          ts-username: testuser
          ts-password: ${{ secrets.TS_Testuser_Password }}
      - name: Test TS Org Teardown
        uses: ./actions/org/cancel
        with:
          ts-org:      testopen01
          ts-username: testuser
          ts-password: ${{ secrets.TS_Testuser_Password }}
      - name: Test Repo Setup
        uses: ./actions/repo/setup
        with:
          temp-org-name:  munderseth
          temp-repo-name: testspace.test.manual
          org-name:       munderseth
          repo-name:      test01
          accesstoken:    ${{ secrets.GH_Admin }}
      - name: TS Run
        uses: ./actions/run
        with:
          ts-org:      testorg
          ts-username: testuser
          ts-password: ${{ secrets.TS_Testuser_Password }}
          gh-repo:     test01
          ts-project:  munderseth:test01
      - name: Delete Testspace project
        uses: ./actions/proj/delete
        with:
          ts-token:   ${{ secrets.TS_Admin }}
          ts-org:     testorg
          ts-project: munderseth:test01
      - name: Test Repo Teardown
        uses: ./actions/repo/teardown
        with:
          org-name:    munderseth
          repo-name:   test01
          accesstoken: ${{ secrets.GH_Admin }}
